{
    "Comment": "Story Refinement Workflow (Automated Testing Version)",
    "StartAt": "AnalyzeStoryWorker",
    "States": {
      "AnalyzeStoryWorker": {
        "Type": "Task",
        "Resource": "${analyze_story_worker_arn}",
        "Next": "TechnicalReview",
        "Catch": [{
          "ErrorEquals": ["States.ALL"],
          "Next": "ErrorState"
        }]
      },
      "TechnicalReview": {
        "Type": "Task",
        "Resource": "${technical_review_arn}",
        "Next": "TechnicalReviewWorker",
        "Catch": [{
          "ErrorEquals": ["States.ALL"],
          "Next": "ErrorState"
        }]
      },
      "TechnicalReviewWorker": {
        "Type": "Task",
        "Resource": "${technical_review_worker_arn}",
        "Next": "TeamEstimation",
        "Catch": [{
          "ErrorEquals": ["States.ALL"],
          "Next": "ErrorState"
        }]
      },
      "TeamEstimation": {
        "Type": "Task",
        "Resource": "${team_estimate_arn}",
        "Next": "TeamEstimationWorker",
        "Catch": [{
          "ErrorEquals": ["States.ALL"],
          "Next": "ErrorState"
        }]
      },
      "TeamEstimationWorker": {
        "Type": "Task",
        "Resource": "${team_estimate_worker_arn}",
        "Next": "CompleteState",
        "Catch": [{
          "ErrorEquals": ["States.ALL"],
          "Next": "ErrorState"
        }]
      },
      "CompleteState": {
        "Type": "Succeed"
      },
      "ErrorState": {
        "Type": "Fail",
        "Error": "WorkflowError",
        "Cause": "An error occurred in the workflow."
      }
    }
}
  